CREATE FUNCTION GetLast12CharsFromGUID (@guid UNIQUEIDENTIFIER)
RETURNS NVARCHAR(12)
AS
BEGIN
	DECLARE @last12chars NVARCHAR(36)
	SET @last12chars = RIGHT(CONVERT(NVARCHAR(36), @guid), 12)
	RETURN @last12chars
END